name: Deploy Next Version
on:
  push:
    branches:
      - main

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Redirect 404 to Index for SPA
        run: cp build/index.html build/404.html

      - name: Deploy nsite
        run: npx -y nsite-cli upload build --verbose --purge --privatekey ${{ secrets.NSITE_KEY }}
